name: PR
on: [pull_request]

jobs:
  lint:
    name: Lint
    uses: networklocum/workflows/.github/workflows/reusable-lint.yml@main
    with:
      black_version: "22.12.0"
      ruff_version: "0.1.11"

  mypy:
    name: Lint
    uses: networklocum/workflows/.github/workflows/reusable-mypy.yml@main
    with:
      python-version: "3.7"
      poetry-version: "1.5.1"

  build-and-test:
    name: Test
    uses: networklocum/workflows/.github/workflows/library-test.yml@main
    with:
      poetry-version: "1.5.1"
      upload-reports: false

  success:
    name: Success
    runs-on: ubuntu-latest
    needs:
      - build-and-test
      - lint
      - mypy
    steps:
      - run: "true"
