name: Build & Push
on:
  push:
    branches:
      - main
      - master
    paths: pyproject.toml

permissions: write-all

jobs:
  build_and_release:
    name: Build & Release
    uses: networklocum/workflows/.github/workflows/library-deploy.yml@main
    secrets: inherit
